//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreedomeF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Behavior", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Behavior : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int totalSubjectField;
        
        private int totalMarkedSubjectField;
        
        private double behaviorMarkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int totalSubject {
            get {
                return this.totalSubjectField;
            }
            set {
                if ((this.totalSubjectField.Equals(value) != true)) {
                    this.totalSubjectField = value;
                    this.RaisePropertyChanged("totalSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int totalMarkedSubject {
            get {
                return this.totalMarkedSubjectField;
            }
            set {
                if ((this.totalMarkedSubjectField.Equals(value) != true)) {
                    this.totalMarkedSubjectField = value;
                    this.RaisePropertyChanged("totalMarkedSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double behaviorMark {
            get {
                return this.behaviorMarkField;
            }
            set {
                if ((this.behaviorMarkField.Equals(value) != true)) {
                    this.behaviorMarkField = value;
                    this.RaisePropertyChanged("behaviorMark");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfGetTeacherComment", Namespace="http://tempuri.org/", ItemName="getTeacherComment")]
    [System.SerializableAttribute()]
    public class ArrayOfGetTeacherComment : System.Collections.Generic.List<FreedomeF.ServiceReference1.getTeacherComment> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="getTeacherComment", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class getTeacherComment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contentCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string teacherIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string contentComment {
            get {
                return this.contentCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.contentCommentField, value) != true)) {
                    this.contentCommentField = value;
                    this.RaisePropertyChanged("contentComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string teacherID {
            get {
                return this.teacherIDField;
            }
            set {
                if ((object.ReferenceEquals(this.teacherIDField, value) != true)) {
                    this.teacherIDField = value;
                    this.RaisePropertyChanged("teacherID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name studentID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBehaviorMark", ReplyAction="*")]
        FreedomeF.ServiceReference1.getBehaviorMarkResponse getBehaviorMark(FreedomeF.ServiceReference1.getBehaviorMarkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBehaviorMark", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference1.getBehaviorMarkResponse> getBehaviorMarkAsync(FreedomeF.ServiceReference1.getBehaviorMarkRequest request);
        
        // CODEGEN: Generating message contract since element name studentID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCommentBehavior", ReplyAction="*")]
        FreedomeF.ServiceReference1.getCommentBehaviorResponse getCommentBehavior(FreedomeF.ServiceReference1.getCommentBehaviorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCommentBehavior", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference1.getCommentBehaviorResponse> getCommentBehaviorAsync(FreedomeF.ServiceReference1.getCommentBehaviorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBehaviorMarkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBehaviorMark", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference1.getBehaviorMarkRequestBody Body;
        
        public getBehaviorMarkRequest() {
        }
        
        public getBehaviorMarkRequest(FreedomeF.ServiceReference1.getBehaviorMarkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getBehaviorMarkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string studentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string semester;
        
        public getBehaviorMarkRequestBody() {
        }
        
        public getBehaviorMarkRequestBody(string studentID, string semester) {
            this.studentID = studentID;
            this.semester = semester;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBehaviorMarkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBehaviorMarkResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference1.getBehaviorMarkResponseBody Body;
        
        public getBehaviorMarkResponse() {
        }
        
        public getBehaviorMarkResponse(FreedomeF.ServiceReference1.getBehaviorMarkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getBehaviorMarkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FreedomeF.ServiceReference1.Behavior getBehaviorMarkResult;
        
        public getBehaviorMarkResponseBody() {
        }
        
        public getBehaviorMarkResponseBody(FreedomeF.ServiceReference1.Behavior getBehaviorMarkResult) {
            this.getBehaviorMarkResult = getBehaviorMarkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCommentBehaviorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCommentBehavior", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference1.getCommentBehaviorRequestBody Body;
        
        public getCommentBehaviorRequest() {
        }
        
        public getCommentBehaviorRequest(FreedomeF.ServiceReference1.getCommentBehaviorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCommentBehaviorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string studentID;
        
        public getCommentBehaviorRequestBody() {
        }
        
        public getCommentBehaviorRequestBody(string studentID) {
            this.studentID = studentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCommentBehaviorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCommentBehaviorResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference1.getCommentBehaviorResponseBody Body;
        
        public getCommentBehaviorResponse() {
        }
        
        public getCommentBehaviorResponse(FreedomeF.ServiceReference1.getCommentBehaviorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCommentBehaviorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FreedomeF.ServiceReference1.ArrayOfGetTeacherComment getCommentBehaviorResult;
        
        public getCommentBehaviorResponseBody() {
        }
        
        public getCommentBehaviorResponseBody(FreedomeF.ServiceReference1.ArrayOfGetTeacherComment getCommentBehaviorResult) {
            this.getCommentBehaviorResult = getCommentBehaviorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : FreedomeF.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<FreedomeF.ServiceReference1.WebService1Soap>, FreedomeF.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference1.getBehaviorMarkResponse FreedomeF.ServiceReference1.WebService1Soap.getBehaviorMark(FreedomeF.ServiceReference1.getBehaviorMarkRequest request) {
            return base.Channel.getBehaviorMark(request);
        }
        
        public FreedomeF.ServiceReference1.Behavior getBehaviorMark(string studentID, string semester) {
            FreedomeF.ServiceReference1.getBehaviorMarkRequest inValue = new FreedomeF.ServiceReference1.getBehaviorMarkRequest();
            inValue.Body = new FreedomeF.ServiceReference1.getBehaviorMarkRequestBody();
            inValue.Body.studentID = studentID;
            inValue.Body.semester = semester;
            FreedomeF.ServiceReference1.getBehaviorMarkResponse retVal = ((FreedomeF.ServiceReference1.WebService1Soap)(this)).getBehaviorMark(inValue);
            return retVal.Body.getBehaviorMarkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference1.getBehaviorMarkResponse> FreedomeF.ServiceReference1.WebService1Soap.getBehaviorMarkAsync(FreedomeF.ServiceReference1.getBehaviorMarkRequest request) {
            return base.Channel.getBehaviorMarkAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference1.getBehaviorMarkResponse> getBehaviorMarkAsync(string studentID, string semester) {
            FreedomeF.ServiceReference1.getBehaviorMarkRequest inValue = new FreedomeF.ServiceReference1.getBehaviorMarkRequest();
            inValue.Body = new FreedomeF.ServiceReference1.getBehaviorMarkRequestBody();
            inValue.Body.studentID = studentID;
            inValue.Body.semester = semester;
            return ((FreedomeF.ServiceReference1.WebService1Soap)(this)).getBehaviorMarkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference1.getCommentBehaviorResponse FreedomeF.ServiceReference1.WebService1Soap.getCommentBehavior(FreedomeF.ServiceReference1.getCommentBehaviorRequest request) {
            return base.Channel.getCommentBehavior(request);
        }
        
        public FreedomeF.ServiceReference1.ArrayOfGetTeacherComment getCommentBehavior(string studentID) {
            FreedomeF.ServiceReference1.getCommentBehaviorRequest inValue = new FreedomeF.ServiceReference1.getCommentBehaviorRequest();
            inValue.Body = new FreedomeF.ServiceReference1.getCommentBehaviorRequestBody();
            inValue.Body.studentID = studentID;
            FreedomeF.ServiceReference1.getCommentBehaviorResponse retVal = ((FreedomeF.ServiceReference1.WebService1Soap)(this)).getCommentBehavior(inValue);
            return retVal.Body.getCommentBehaviorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference1.getCommentBehaviorResponse> FreedomeF.ServiceReference1.WebService1Soap.getCommentBehaviorAsync(FreedomeF.ServiceReference1.getCommentBehaviorRequest request) {
            return base.Channel.getCommentBehaviorAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference1.getCommentBehaviorResponse> getCommentBehaviorAsync(string studentID) {
            FreedomeF.ServiceReference1.getCommentBehaviorRequest inValue = new FreedomeF.ServiceReference1.getCommentBehaviorRequest();
            inValue.Body = new FreedomeF.ServiceReference1.getCommentBehaviorRequestBody();
            inValue.Body.studentID = studentID;
            return ((FreedomeF.ServiceReference1.WebService1Soap)(this)).getCommentBehaviorAsync(inValue);
        }
    }
}
