//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreedomeF.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.SAPISoap")]
    public interface SAPISoap {
        
        // CODEGEN: Generating message contract since element name GetStudenK10JSResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudenK10JS", ReplyAction="*")]
        FreedomeF.ServiceReference2.GetStudenK10JSResponse GetStudenK10JS(FreedomeF.ServiceReference2.GetStudenK10JSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudenK10JS", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.GetStudenK10JSResponse> GetStudenK10JSAsync(FreedomeF.ServiceReference2.GetStudenK10JSRequest request);
        
        // CODEGEN: Generating message contract since element name rollNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentById", ReplyAction="*")]
        FreedomeF.ServiceReference2.GetStudentByIdResponse GetStudentById(FreedomeF.ServiceReference2.GetStudentByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentById", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.GetStudentByIdResponse> GetStudentByIdAsync(FreedomeF.ServiceReference2.GetStudentByIdRequest request);
        
        // CODEGEN: Generating message contract since element name rollNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckBlance", ReplyAction="*")]
        FreedomeF.ServiceReference2.CheckBlanceResponse CheckBlance(FreedomeF.ServiceReference2.CheckBlanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckBlance", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.CheckBlanceResponse> CheckBlanceAsync(FreedomeF.ServiceReference2.CheckBlanceRequest request);
        
        // CODEGEN: Generating message contract since element name rollnumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetriveImage", ReplyAction="*")]
        FreedomeF.ServiceReference2.RetriveImageResponse RetriveImage(FreedomeF.ServiceReference2.RetriveImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetriveImage", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.RetriveImageResponse> RetriveImageAsync(FreedomeF.ServiceReference2.RetriveImageRequest request);
        
        // CODEGEN: Generating message contract since element name rollNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getscheduleExam", ReplyAction="*")]
        FreedomeF.ServiceReference2.getscheduleExamResponse getscheduleExam(FreedomeF.ServiceReference2.getscheduleExamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getscheduleExam", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getscheduleExamResponse> getscheduleExamAsync(FreedomeF.ServiceReference2.getscheduleExamRequest request);
        
        // CODEGEN: Generating message contract since element name rollNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInfoToday", ReplyAction="*")]
        FreedomeF.ServiceReference2.getInfoTodayResponse getInfoToday(FreedomeF.ServiceReference2.getInfoTodayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInfoToday", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getInfoTodayResponse> getInfoTodayAsync(FreedomeF.ServiceReference2.getInfoTodayRequest request);
        
        // CODEGEN: Generating message contract since element name rollNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCurriculum", ReplyAction="*")]
        FreedomeF.ServiceReference2.getCurriculumResponse getCurriculum(FreedomeF.ServiceReference2.getCurriculumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCurriculum", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getCurriculumResponse> getCurriculumAsync(FreedomeF.ServiceReference2.getCurriculumRequest request);
        
        // CODEGEN: Generating message contract since element name rollNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWeeklyReport", ReplyAction="*")]
        FreedomeF.ServiceReference2.getWeeklyReportResponse getWeeklyReport(FreedomeF.ServiceReference2.getWeeklyReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWeeklyReport", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getWeeklyReportResponse> getWeeklyReportAsync(FreedomeF.ServiceReference2.getWeeklyReportRequest request);
        
        // CODEGEN: Generating message contract since element name rollNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAttendanceMark", ReplyAction="*")]
        FreedomeF.ServiceReference2.getAttendanceMarkResponse getAttendanceMark(FreedomeF.ServiceReference2.getAttendanceMarkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAttendanceMark", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getAttendanceMarkResponse> getAttendanceMarkAsync(FreedomeF.ServiceReference2.getAttendanceMarkRequest request);
        
        // CODEGEN: Generating message contract since element name rollNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGPA", ReplyAction="*")]
        FreedomeF.ServiceReference2.getGPAResponse getGPA(FreedomeF.ServiceReference2.getGPARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGPA", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getGPAResponse> getGPAAsync(FreedomeF.ServiceReference2.getGPARequest request);
        
        // CODEGEN: Generating message contract since element name rollNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTimeTable", ReplyAction="*")]
        FreedomeF.ServiceReference2.getTimeTableResponse getTimeTable(FreedomeF.ServiceReference2.getTimeTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTimeTable", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getTimeTableResponse> getTimeTableAsync(FreedomeF.ServiceReference2.getTimeTableRequest request);
        
        // CODEGEN: Generating message contract since element name rollNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFailCourse", ReplyAction="*")]
        FreedomeF.ServiceReference2.getFailCourseResponse getFailCourse(FreedomeF.ServiceReference2.getFailCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFailCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getFailCourseResponse> getFailCourseAsync(FreedomeF.ServiceReference2.getFailCourseRequest request);
        
        // CODEGEN: Generating message contract since element name rollNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPassCourse", ReplyAction="*")]
        FreedomeF.ServiceReference2.getPassCourseResponse getPassCourse(FreedomeF.ServiceReference2.getPassCourseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPassCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getPassCourseResponse> getPassCourseAsync(FreedomeF.ServiceReference2.getPassCourseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudenK10JSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudenK10JS", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.GetStudenK10JSRequestBody Body;
        
        public GetStudenK10JSRequest() {
        }
        
        public GetStudenK10JSRequest(FreedomeF.ServiceReference2.GetStudenK10JSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStudenK10JSRequestBody {
        
        public GetStudenK10JSRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudenK10JSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudenK10JSResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.GetStudenK10JSResponseBody Body;
        
        public GetStudenK10JSResponse() {
        }
        
        public GetStudenK10JSResponse(FreedomeF.ServiceReference2.GetStudenK10JSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudenK10JSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStudenK10JSResult;
        
        public GetStudenK10JSResponseBody() {
        }
        
        public GetStudenK10JSResponseBody(string GetStudenK10JSResult) {
            this.GetStudenK10JSResult = GetStudenK10JSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentById", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.GetStudentByIdRequestBody Body;
        
        public GetStudentByIdRequest() {
        }
        
        public GetStudentByIdRequest(FreedomeF.ServiceReference2.GetStudentByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollNumber;
        
        public GetStudentByIdRequestBody() {
        }
        
        public GetStudentByIdRequestBody(string rollNumber) {
            this.rollNumber = rollNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.GetStudentByIdResponseBody Body;
        
        public GetStudentByIdResponse() {
        }
        
        public GetStudentByIdResponse(FreedomeF.ServiceReference2.GetStudentByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStudentByIdResult;
        
        public GetStudentByIdResponseBody() {
        }
        
        public GetStudentByIdResponseBody(string GetStudentByIdResult) {
            this.GetStudentByIdResult = GetStudentByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckBlanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckBlance", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.CheckBlanceRequestBody Body;
        
        public CheckBlanceRequest() {
        }
        
        public CheckBlanceRequest(FreedomeF.ServiceReference2.CheckBlanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckBlanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollNumber;
        
        public CheckBlanceRequestBody() {
        }
        
        public CheckBlanceRequestBody(string rollNumber) {
            this.rollNumber = rollNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckBlanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckBlanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.CheckBlanceResponseBody Body;
        
        public CheckBlanceResponse() {
        }
        
        public CheckBlanceResponse(FreedomeF.ServiceReference2.CheckBlanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckBlanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal CheckBlanceResult;
        
        public CheckBlanceResponseBody() {
        }
        
        public CheckBlanceResponseBody(decimal CheckBlanceResult) {
            this.CheckBlanceResult = CheckBlanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetriveImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetriveImage", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.RetriveImageRequestBody Body;
        
        public RetriveImageRequest() {
        }
        
        public RetriveImageRequest(FreedomeF.ServiceReference2.RetriveImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetriveImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollnumber;
        
        public RetriveImageRequestBody() {
        }
        
        public RetriveImageRequestBody(string rollnumber) {
            this.rollnumber = rollnumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetriveImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetriveImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.RetriveImageResponseBody Body;
        
        public RetriveImageResponse() {
        }
        
        public RetriveImageResponse(FreedomeF.ServiceReference2.RetriveImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetriveImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] RetriveImageResult;
        
        public RetriveImageResponseBody() {
        }
        
        public RetriveImageResponseBody(byte[] RetriveImageResult) {
            this.RetriveImageResult = RetriveImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getscheduleExamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getscheduleExam", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getscheduleExamRequestBody Body;
        
        public getscheduleExamRequest() {
        }
        
        public getscheduleExamRequest(FreedomeF.ServiceReference2.getscheduleExamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getscheduleExamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime date;
        
        public getscheduleExamRequestBody() {
        }
        
        public getscheduleExamRequestBody(string rollNumber, System.DateTime date) {
            this.rollNumber = rollNumber;
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getscheduleExamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getscheduleExamResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getscheduleExamResponseBody Body;
        
        public getscheduleExamResponse() {
        }
        
        public getscheduleExamResponse(FreedomeF.ServiceReference2.getscheduleExamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getscheduleExamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getscheduleExamResult;
        
        public getscheduleExamResponseBody() {
        }
        
        public getscheduleExamResponseBody(string getscheduleExamResult) {
            this.getscheduleExamResult = getscheduleExamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInfoTodayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoToday", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getInfoTodayRequestBody Body;
        
        public getInfoTodayRequest() {
        }
        
        public getInfoTodayRequest(FreedomeF.ServiceReference2.getInfoTodayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInfoTodayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime date;
        
        public getInfoTodayRequestBody() {
        }
        
        public getInfoTodayRequestBody(string rollNumber, System.DateTime date) {
            this.rollNumber = rollNumber;
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInfoTodayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoTodayResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getInfoTodayResponseBody Body;
        
        public getInfoTodayResponse() {
        }
        
        public getInfoTodayResponse(FreedomeF.ServiceReference2.getInfoTodayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInfoTodayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getInfoTodayResult;
        
        public getInfoTodayResponseBody() {
        }
        
        public getInfoTodayResponseBody(string getInfoTodayResult) {
            this.getInfoTodayResult = getInfoTodayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCurriculumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCurriculum", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getCurriculumRequestBody Body;
        
        public getCurriculumRequest() {
        }
        
        public getCurriculumRequest(FreedomeF.ServiceReference2.getCurriculumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCurriculumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollNumber;
        
        public getCurriculumRequestBody() {
        }
        
        public getCurriculumRequestBody(string rollNumber) {
            this.rollNumber = rollNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCurriculumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCurriculumResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getCurriculumResponseBody Body;
        
        public getCurriculumResponse() {
        }
        
        public getCurriculumResponse(FreedomeF.ServiceReference2.getCurriculumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCurriculumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getCurriculumResult;
        
        public getCurriculumResponseBody() {
        }
        
        public getCurriculumResponseBody(string getCurriculumResult) {
            this.getCurriculumResult = getCurriculumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeeklyReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWeeklyReport", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getWeeklyReportRequestBody Body;
        
        public getWeeklyReportRequest() {
        }
        
        public getWeeklyReportRequest(FreedomeF.ServiceReference2.getWeeklyReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWeeklyReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime sDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime eDateTime;
        
        public getWeeklyReportRequestBody() {
        }
        
        public getWeeklyReportRequestBody(string rollNumber, System.DateTime sDateTime, System.DateTime eDateTime) {
            this.rollNumber = rollNumber;
            this.sDateTime = sDateTime;
            this.eDateTime = eDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeeklyReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWeeklyReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getWeeklyReportResponseBody Body;
        
        public getWeeklyReportResponse() {
        }
        
        public getWeeklyReportResponse(FreedomeF.ServiceReference2.getWeeklyReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWeeklyReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getWeeklyReportResult;
        
        public getWeeklyReportResponseBody() {
        }
        
        public getWeeklyReportResponseBody(string getWeeklyReportResult) {
            this.getWeeklyReportResult = getWeeklyReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAttendanceMarkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAttendanceMark", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getAttendanceMarkRequestBody Body;
        
        public getAttendanceMarkRequest() {
        }
        
        public getAttendanceMarkRequest(FreedomeF.ServiceReference2.getAttendanceMarkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAttendanceMarkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string semsester;
        
        public getAttendanceMarkRequestBody() {
        }
        
        public getAttendanceMarkRequestBody(string rollNumber, string semsester) {
            this.rollNumber = rollNumber;
            this.semsester = semsester;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAttendanceMarkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAttendanceMarkResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getAttendanceMarkResponseBody Body;
        
        public getAttendanceMarkResponse() {
        }
        
        public getAttendanceMarkResponse(FreedomeF.ServiceReference2.getAttendanceMarkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAttendanceMarkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getAttendanceMarkResult;
        
        public getAttendanceMarkResponseBody() {
        }
        
        public getAttendanceMarkResponseBody(string getAttendanceMarkResult) {
            this.getAttendanceMarkResult = getAttendanceMarkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGPARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGPA", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getGPARequestBody Body;
        
        public getGPARequest() {
        }
        
        public getGPARequest(FreedomeF.ServiceReference2.getGPARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGPARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string semsester;
        
        public getGPARequestBody() {
        }
        
        public getGPARequestBody(string rollNumber, string semsester) {
            this.rollNumber = rollNumber;
            this.semsester = semsester;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGPAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGPAResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getGPAResponseBody Body;
        
        public getGPAResponse() {
        }
        
        public getGPAResponse(FreedomeF.ServiceReference2.getGPAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGPAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getGPAResult;
        
        public getGPAResponseBody() {
        }
        
        public getGPAResponseBody(string getGPAResult) {
            this.getGPAResult = getGPAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTimeTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTimeTable", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getTimeTableRequestBody Body;
        
        public getTimeTableRequest() {
        }
        
        public getTimeTableRequest(FreedomeF.ServiceReference2.getTimeTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTimeTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime SDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime eDate;
        
        public getTimeTableRequestBody() {
        }
        
        public getTimeTableRequestBody(string rollNumber, System.DateTime SDate, System.DateTime eDate) {
            this.rollNumber = rollNumber;
            this.SDate = SDate;
            this.eDate = eDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTimeTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTimeTableResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getTimeTableResponseBody Body;
        
        public getTimeTableResponse() {
        }
        
        public getTimeTableResponse(FreedomeF.ServiceReference2.getTimeTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTimeTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTimeTableResult;
        
        public getTimeTableResponseBody() {
        }
        
        public getTimeTableResponseBody(string getTimeTableResult) {
            this.getTimeTableResult = getTimeTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFailCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFailCourse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getFailCourseRequestBody Body;
        
        public getFailCourseRequest() {
        }
        
        public getFailCourseRequest(FreedomeF.ServiceReference2.getFailCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFailCourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollNumber;
        
        public getFailCourseRequestBody() {
        }
        
        public getFailCourseRequestBody(string rollNumber) {
            this.rollNumber = rollNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFailCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFailCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getFailCourseResponseBody Body;
        
        public getFailCourseResponse() {
        }
        
        public getFailCourseResponse(FreedomeF.ServiceReference2.getFailCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFailCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFailCourseResult;
        
        public getFailCourseResponseBody() {
        }
        
        public getFailCourseResponseBody(string getFailCourseResult) {
            this.getFailCourseResult = getFailCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPassCourseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPassCourse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getPassCourseRequestBody Body;
        
        public getPassCourseRequest() {
        }
        
        public getPassCourseRequest(FreedomeF.ServiceReference2.getPassCourseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPassCourseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rollNumber;
        
        public getPassCourseRequestBody() {
        }
        
        public getPassCourseRequestBody(string rollNumber) {
            this.rollNumber = rollNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPassCourseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPassCourseResponse", Namespace="http://tempuri.org/", Order=0)]
        public FreedomeF.ServiceReference2.getPassCourseResponseBody Body;
        
        public getPassCourseResponse() {
        }
        
        public getPassCourseResponse(FreedomeF.ServiceReference2.getPassCourseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPassCourseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPassCourseResult;
        
        public getPassCourseResponseBody() {
        }
        
        public getPassCourseResponseBody(string getPassCourseResult) {
            this.getPassCourseResult = getPassCourseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SAPISoapChannel : FreedomeF.ServiceReference2.SAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SAPISoapClient : System.ServiceModel.ClientBase<FreedomeF.ServiceReference2.SAPISoap>, FreedomeF.ServiceReference2.SAPISoap {
        
        public SAPISoapClient() {
        }
        
        public SAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference2.GetStudenK10JSResponse FreedomeF.ServiceReference2.SAPISoap.GetStudenK10JS(FreedomeF.ServiceReference2.GetStudenK10JSRequest request) {
            return base.Channel.GetStudenK10JS(request);
        }
        
        public string GetStudenK10JS() {
            FreedomeF.ServiceReference2.GetStudenK10JSRequest inValue = new FreedomeF.ServiceReference2.GetStudenK10JSRequest();
            inValue.Body = new FreedomeF.ServiceReference2.GetStudenK10JSRequestBody();
            FreedomeF.ServiceReference2.GetStudenK10JSResponse retVal = ((FreedomeF.ServiceReference2.SAPISoap)(this)).GetStudenK10JS(inValue);
            return retVal.Body.GetStudenK10JSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.GetStudenK10JSResponse> FreedomeF.ServiceReference2.SAPISoap.GetStudenK10JSAsync(FreedomeF.ServiceReference2.GetStudenK10JSRequest request) {
            return base.Channel.GetStudenK10JSAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference2.GetStudenK10JSResponse> GetStudenK10JSAsync() {
            FreedomeF.ServiceReference2.GetStudenK10JSRequest inValue = new FreedomeF.ServiceReference2.GetStudenK10JSRequest();
            inValue.Body = new FreedomeF.ServiceReference2.GetStudenK10JSRequestBody();
            return ((FreedomeF.ServiceReference2.SAPISoap)(this)).GetStudenK10JSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference2.GetStudentByIdResponse FreedomeF.ServiceReference2.SAPISoap.GetStudentById(FreedomeF.ServiceReference2.GetStudentByIdRequest request) {
            return base.Channel.GetStudentById(request);
        }
        
        public string GetStudentById(string rollNumber) {
            FreedomeF.ServiceReference2.GetStudentByIdRequest inValue = new FreedomeF.ServiceReference2.GetStudentByIdRequest();
            inValue.Body = new FreedomeF.ServiceReference2.GetStudentByIdRequestBody();
            inValue.Body.rollNumber = rollNumber;
            FreedomeF.ServiceReference2.GetStudentByIdResponse retVal = ((FreedomeF.ServiceReference2.SAPISoap)(this)).GetStudentById(inValue);
            return retVal.Body.GetStudentByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.GetStudentByIdResponse> FreedomeF.ServiceReference2.SAPISoap.GetStudentByIdAsync(FreedomeF.ServiceReference2.GetStudentByIdRequest request) {
            return base.Channel.GetStudentByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference2.GetStudentByIdResponse> GetStudentByIdAsync(string rollNumber) {
            FreedomeF.ServiceReference2.GetStudentByIdRequest inValue = new FreedomeF.ServiceReference2.GetStudentByIdRequest();
            inValue.Body = new FreedomeF.ServiceReference2.GetStudentByIdRequestBody();
            inValue.Body.rollNumber = rollNumber;
            return ((FreedomeF.ServiceReference2.SAPISoap)(this)).GetStudentByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference2.CheckBlanceResponse FreedomeF.ServiceReference2.SAPISoap.CheckBlance(FreedomeF.ServiceReference2.CheckBlanceRequest request) {
            return base.Channel.CheckBlance(request);
        }
        
        public decimal CheckBlance(string rollNumber) {
            FreedomeF.ServiceReference2.CheckBlanceRequest inValue = new FreedomeF.ServiceReference2.CheckBlanceRequest();
            inValue.Body = new FreedomeF.ServiceReference2.CheckBlanceRequestBody();
            inValue.Body.rollNumber = rollNumber;
            FreedomeF.ServiceReference2.CheckBlanceResponse retVal = ((FreedomeF.ServiceReference2.SAPISoap)(this)).CheckBlance(inValue);
            return retVal.Body.CheckBlanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.CheckBlanceResponse> FreedomeF.ServiceReference2.SAPISoap.CheckBlanceAsync(FreedomeF.ServiceReference2.CheckBlanceRequest request) {
            return base.Channel.CheckBlanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference2.CheckBlanceResponse> CheckBlanceAsync(string rollNumber) {
            FreedomeF.ServiceReference2.CheckBlanceRequest inValue = new FreedomeF.ServiceReference2.CheckBlanceRequest();
            inValue.Body = new FreedomeF.ServiceReference2.CheckBlanceRequestBody();
            inValue.Body.rollNumber = rollNumber;
            return ((FreedomeF.ServiceReference2.SAPISoap)(this)).CheckBlanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference2.RetriveImageResponse FreedomeF.ServiceReference2.SAPISoap.RetriveImage(FreedomeF.ServiceReference2.RetriveImageRequest request) {
            return base.Channel.RetriveImage(request);
        }
        
        public byte[] RetriveImage(string rollnumber) {
            FreedomeF.ServiceReference2.RetriveImageRequest inValue = new FreedomeF.ServiceReference2.RetriveImageRequest();
            inValue.Body = new FreedomeF.ServiceReference2.RetriveImageRequestBody();
            inValue.Body.rollnumber = rollnumber;
            FreedomeF.ServiceReference2.RetriveImageResponse retVal = ((FreedomeF.ServiceReference2.SAPISoap)(this)).RetriveImage(inValue);
            return retVal.Body.RetriveImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.RetriveImageResponse> FreedomeF.ServiceReference2.SAPISoap.RetriveImageAsync(FreedomeF.ServiceReference2.RetriveImageRequest request) {
            return base.Channel.RetriveImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference2.RetriveImageResponse> RetriveImageAsync(string rollnumber) {
            FreedomeF.ServiceReference2.RetriveImageRequest inValue = new FreedomeF.ServiceReference2.RetriveImageRequest();
            inValue.Body = new FreedomeF.ServiceReference2.RetriveImageRequestBody();
            inValue.Body.rollnumber = rollnumber;
            return ((FreedomeF.ServiceReference2.SAPISoap)(this)).RetriveImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference2.getscheduleExamResponse FreedomeF.ServiceReference2.SAPISoap.getscheduleExam(FreedomeF.ServiceReference2.getscheduleExamRequest request) {
            return base.Channel.getscheduleExam(request);
        }
        
        public string getscheduleExam(string rollNumber, System.DateTime date) {
            FreedomeF.ServiceReference2.getscheduleExamRequest inValue = new FreedomeF.ServiceReference2.getscheduleExamRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getscheduleExamRequestBody();
            inValue.Body.rollNumber = rollNumber;
            inValue.Body.date = date;
            FreedomeF.ServiceReference2.getscheduleExamResponse retVal = ((FreedomeF.ServiceReference2.SAPISoap)(this)).getscheduleExam(inValue);
            return retVal.Body.getscheduleExamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getscheduleExamResponse> FreedomeF.ServiceReference2.SAPISoap.getscheduleExamAsync(FreedomeF.ServiceReference2.getscheduleExamRequest request) {
            return base.Channel.getscheduleExamAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getscheduleExamResponse> getscheduleExamAsync(string rollNumber, System.DateTime date) {
            FreedomeF.ServiceReference2.getscheduleExamRequest inValue = new FreedomeF.ServiceReference2.getscheduleExamRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getscheduleExamRequestBody();
            inValue.Body.rollNumber = rollNumber;
            inValue.Body.date = date;
            return ((FreedomeF.ServiceReference2.SAPISoap)(this)).getscheduleExamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference2.getInfoTodayResponse FreedomeF.ServiceReference2.SAPISoap.getInfoToday(FreedomeF.ServiceReference2.getInfoTodayRequest request) {
            return base.Channel.getInfoToday(request);
        }
        
        public string getInfoToday(string rollNumber, System.DateTime date) {
            FreedomeF.ServiceReference2.getInfoTodayRequest inValue = new FreedomeF.ServiceReference2.getInfoTodayRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getInfoTodayRequestBody();
            inValue.Body.rollNumber = rollNumber;
            inValue.Body.date = date;
            FreedomeF.ServiceReference2.getInfoTodayResponse retVal = ((FreedomeF.ServiceReference2.SAPISoap)(this)).getInfoToday(inValue);
            return retVal.Body.getInfoTodayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getInfoTodayResponse> FreedomeF.ServiceReference2.SAPISoap.getInfoTodayAsync(FreedomeF.ServiceReference2.getInfoTodayRequest request) {
            return base.Channel.getInfoTodayAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getInfoTodayResponse> getInfoTodayAsync(string rollNumber, System.DateTime date) {
            FreedomeF.ServiceReference2.getInfoTodayRequest inValue = new FreedomeF.ServiceReference2.getInfoTodayRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getInfoTodayRequestBody();
            inValue.Body.rollNumber = rollNumber;
            inValue.Body.date = date;
            return ((FreedomeF.ServiceReference2.SAPISoap)(this)).getInfoTodayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference2.getCurriculumResponse FreedomeF.ServiceReference2.SAPISoap.getCurriculum(FreedomeF.ServiceReference2.getCurriculumRequest request) {
            return base.Channel.getCurriculum(request);
        }
        
        public string getCurriculum(string rollNumber) {
            FreedomeF.ServiceReference2.getCurriculumRequest inValue = new FreedomeF.ServiceReference2.getCurriculumRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getCurriculumRequestBody();
            inValue.Body.rollNumber = rollNumber;
            FreedomeF.ServiceReference2.getCurriculumResponse retVal = ((FreedomeF.ServiceReference2.SAPISoap)(this)).getCurriculum(inValue);
            return retVal.Body.getCurriculumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getCurriculumResponse> FreedomeF.ServiceReference2.SAPISoap.getCurriculumAsync(FreedomeF.ServiceReference2.getCurriculumRequest request) {
            return base.Channel.getCurriculumAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getCurriculumResponse> getCurriculumAsync(string rollNumber) {
            FreedomeF.ServiceReference2.getCurriculumRequest inValue = new FreedomeF.ServiceReference2.getCurriculumRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getCurriculumRequestBody();
            inValue.Body.rollNumber = rollNumber;
            return ((FreedomeF.ServiceReference2.SAPISoap)(this)).getCurriculumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference2.getWeeklyReportResponse FreedomeF.ServiceReference2.SAPISoap.getWeeklyReport(FreedomeF.ServiceReference2.getWeeklyReportRequest request) {
            return base.Channel.getWeeklyReport(request);
        }
        
        public string getWeeklyReport(string rollNumber, System.DateTime sDateTime, System.DateTime eDateTime) {
            FreedomeF.ServiceReference2.getWeeklyReportRequest inValue = new FreedomeF.ServiceReference2.getWeeklyReportRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getWeeklyReportRequestBody();
            inValue.Body.rollNumber = rollNumber;
            inValue.Body.sDateTime = sDateTime;
            inValue.Body.eDateTime = eDateTime;
            FreedomeF.ServiceReference2.getWeeklyReportResponse retVal = ((FreedomeF.ServiceReference2.SAPISoap)(this)).getWeeklyReport(inValue);
            return retVal.Body.getWeeklyReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getWeeklyReportResponse> FreedomeF.ServiceReference2.SAPISoap.getWeeklyReportAsync(FreedomeF.ServiceReference2.getWeeklyReportRequest request) {
            return base.Channel.getWeeklyReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getWeeklyReportResponse> getWeeklyReportAsync(string rollNumber, System.DateTime sDateTime, System.DateTime eDateTime) {
            FreedomeF.ServiceReference2.getWeeklyReportRequest inValue = new FreedomeF.ServiceReference2.getWeeklyReportRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getWeeklyReportRequestBody();
            inValue.Body.rollNumber = rollNumber;
            inValue.Body.sDateTime = sDateTime;
            inValue.Body.eDateTime = eDateTime;
            return ((FreedomeF.ServiceReference2.SAPISoap)(this)).getWeeklyReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference2.getAttendanceMarkResponse FreedomeF.ServiceReference2.SAPISoap.getAttendanceMark(FreedomeF.ServiceReference2.getAttendanceMarkRequest request) {
            return base.Channel.getAttendanceMark(request);
        }
        
        public string getAttendanceMark(string rollNumber, string semsester) {
            FreedomeF.ServiceReference2.getAttendanceMarkRequest inValue = new FreedomeF.ServiceReference2.getAttendanceMarkRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getAttendanceMarkRequestBody();
            inValue.Body.rollNumber = rollNumber;
            inValue.Body.semsester = semsester;
            FreedomeF.ServiceReference2.getAttendanceMarkResponse retVal = ((FreedomeF.ServiceReference2.SAPISoap)(this)).getAttendanceMark(inValue);
            return retVal.Body.getAttendanceMarkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getAttendanceMarkResponse> FreedomeF.ServiceReference2.SAPISoap.getAttendanceMarkAsync(FreedomeF.ServiceReference2.getAttendanceMarkRequest request) {
            return base.Channel.getAttendanceMarkAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getAttendanceMarkResponse> getAttendanceMarkAsync(string rollNumber, string semsester) {
            FreedomeF.ServiceReference2.getAttendanceMarkRequest inValue = new FreedomeF.ServiceReference2.getAttendanceMarkRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getAttendanceMarkRequestBody();
            inValue.Body.rollNumber = rollNumber;
            inValue.Body.semsester = semsester;
            return ((FreedomeF.ServiceReference2.SAPISoap)(this)).getAttendanceMarkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference2.getGPAResponse FreedomeF.ServiceReference2.SAPISoap.getGPA(FreedomeF.ServiceReference2.getGPARequest request) {
            return base.Channel.getGPA(request);
        }
        
        public string getGPA(string rollNumber, string semsester) {
            FreedomeF.ServiceReference2.getGPARequest inValue = new FreedomeF.ServiceReference2.getGPARequest();
            inValue.Body = new FreedomeF.ServiceReference2.getGPARequestBody();
            inValue.Body.rollNumber = rollNumber;
            inValue.Body.semsester = semsester;
            FreedomeF.ServiceReference2.getGPAResponse retVal = ((FreedomeF.ServiceReference2.SAPISoap)(this)).getGPA(inValue);
            return retVal.Body.getGPAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getGPAResponse> FreedomeF.ServiceReference2.SAPISoap.getGPAAsync(FreedomeF.ServiceReference2.getGPARequest request) {
            return base.Channel.getGPAAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getGPAResponse> getGPAAsync(string rollNumber, string semsester) {
            FreedomeF.ServiceReference2.getGPARequest inValue = new FreedomeF.ServiceReference2.getGPARequest();
            inValue.Body = new FreedomeF.ServiceReference2.getGPARequestBody();
            inValue.Body.rollNumber = rollNumber;
            inValue.Body.semsester = semsester;
            return ((FreedomeF.ServiceReference2.SAPISoap)(this)).getGPAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference2.getTimeTableResponse FreedomeF.ServiceReference2.SAPISoap.getTimeTable(FreedomeF.ServiceReference2.getTimeTableRequest request) {
            return base.Channel.getTimeTable(request);
        }
        
        public string getTimeTable(string rollNumber, System.DateTime SDate, System.DateTime eDate) {
            FreedomeF.ServiceReference2.getTimeTableRequest inValue = new FreedomeF.ServiceReference2.getTimeTableRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getTimeTableRequestBody();
            inValue.Body.rollNumber = rollNumber;
            inValue.Body.SDate = SDate;
            inValue.Body.eDate = eDate;
            FreedomeF.ServiceReference2.getTimeTableResponse retVal = ((FreedomeF.ServiceReference2.SAPISoap)(this)).getTimeTable(inValue);
            return retVal.Body.getTimeTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getTimeTableResponse> FreedomeF.ServiceReference2.SAPISoap.getTimeTableAsync(FreedomeF.ServiceReference2.getTimeTableRequest request) {
            return base.Channel.getTimeTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getTimeTableResponse> getTimeTableAsync(string rollNumber, System.DateTime SDate, System.DateTime eDate) {
            FreedomeF.ServiceReference2.getTimeTableRequest inValue = new FreedomeF.ServiceReference2.getTimeTableRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getTimeTableRequestBody();
            inValue.Body.rollNumber = rollNumber;
            inValue.Body.SDate = SDate;
            inValue.Body.eDate = eDate;
            return ((FreedomeF.ServiceReference2.SAPISoap)(this)).getTimeTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference2.getFailCourseResponse FreedomeF.ServiceReference2.SAPISoap.getFailCourse(FreedomeF.ServiceReference2.getFailCourseRequest request) {
            return base.Channel.getFailCourse(request);
        }
        
        public string getFailCourse(string rollNumber) {
            FreedomeF.ServiceReference2.getFailCourseRequest inValue = new FreedomeF.ServiceReference2.getFailCourseRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getFailCourseRequestBody();
            inValue.Body.rollNumber = rollNumber;
            FreedomeF.ServiceReference2.getFailCourseResponse retVal = ((FreedomeF.ServiceReference2.SAPISoap)(this)).getFailCourse(inValue);
            return retVal.Body.getFailCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getFailCourseResponse> FreedomeF.ServiceReference2.SAPISoap.getFailCourseAsync(FreedomeF.ServiceReference2.getFailCourseRequest request) {
            return base.Channel.getFailCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getFailCourseResponse> getFailCourseAsync(string rollNumber) {
            FreedomeF.ServiceReference2.getFailCourseRequest inValue = new FreedomeF.ServiceReference2.getFailCourseRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getFailCourseRequestBody();
            inValue.Body.rollNumber = rollNumber;
            return ((FreedomeF.ServiceReference2.SAPISoap)(this)).getFailCourseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FreedomeF.ServiceReference2.getPassCourseResponse FreedomeF.ServiceReference2.SAPISoap.getPassCourse(FreedomeF.ServiceReference2.getPassCourseRequest request) {
            return base.Channel.getPassCourse(request);
        }
        
        public string getPassCourse(string rollNumber) {
            FreedomeF.ServiceReference2.getPassCourseRequest inValue = new FreedomeF.ServiceReference2.getPassCourseRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getPassCourseRequestBody();
            inValue.Body.rollNumber = rollNumber;
            FreedomeF.ServiceReference2.getPassCourseResponse retVal = ((FreedomeF.ServiceReference2.SAPISoap)(this)).getPassCourse(inValue);
            return retVal.Body.getPassCourseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getPassCourseResponse> FreedomeF.ServiceReference2.SAPISoap.getPassCourseAsync(FreedomeF.ServiceReference2.getPassCourseRequest request) {
            return base.Channel.getPassCourseAsync(request);
        }
        
        public System.Threading.Tasks.Task<FreedomeF.ServiceReference2.getPassCourseResponse> getPassCourseAsync(string rollNumber) {
            FreedomeF.ServiceReference2.getPassCourseRequest inValue = new FreedomeF.ServiceReference2.getPassCourseRequest();
            inValue.Body = new FreedomeF.ServiceReference2.getPassCourseRequestBody();
            inValue.Body.rollNumber = rollNumber;
            return ((FreedomeF.ServiceReference2.SAPISoap)(this)).getPassCourseAsync(inValue);
        }
    }
}
